### ISSUE TITLE
Overspecified detail in "Interval"

### ISSUE THREAD

**Issue by vog** [sgillies/geojson-events#10]
The current draft states:

> An interval MUST NOT have more than one "start" member or more than one "end" member.

It is not clear to me what is meant by this, because it is not clear how there could ever be multiple "start" or "end" members by accident:

* Since "start" and "end" are keys in a JSON object, the JSON standard already ensures that they cannot occur more than once.
* Also, the value of "start" and "end" are defined to be strings (in date-time format), so they aren't arrays.

So what is the intention behind this rule? If it is about making clear that type "Interval" means a single interval and not a multi-interval, this should be stated more clearly. Otherwise, I propose to simply remove this sentence, to avoid confusion.

**Comment by sgillies** [comment]
@vog [I-JSON](https://tools.ietf.org/html/rfc7493#section-2.3) rules out duplicate keys but I'm not certain that other JSON standards adequately do.
