### ISSUE TITLE
GeoJSON-T

### ISSUE THREAD

**Issue by todrobbins** [sgillies/geojson-events#8]
I imagine you are familiar with @kgeographer's work on [GeoJSON-T and Topotime](https://github.com/kgeographer/topotime). I'm curious how `geojson-events` and Grossner's efforts could be unified, although I understand that events are more general in nature.

Cheers!

**Comment by todrobbins** [comment]
See also: https://github.com/kgeographer/topotime/wiki

**Comment by kgeographer** [comment]
@todrobbins Thanks for adding these links. I'm now referring to Topotime as an umbrella project name, the first effort for which is a GeoJSON extension I call GeoJSON-T. It's very much work in progress, responding particularly to requirements of historical gazetteers, and it appears it will work well for "journeys, routes, and flows" as well. I have a Dec 15 deadline to [show how this will work practically](http://commons.pelagios.org/2016/07/linking-linked-places-modeling-historical-movement/), with exemplar data and software to parse and render it.

Of course I am delighted that work on geojson-events is resuming and will watch the repos for developments.
