### ISSUE TITLE
GeoJSON-LD Extension?

### ISSUE THREAD

**Issue by ekansa** [sgillies/geojson-events#9]
Hi Sean. This seems to directly follow this discussion: https://github.com/geojson/geojson-ld/labels/time

Are you going to add this as an optional extension to the proposed GeoJSON-LD (http://geojson.org/geojson-ld/) vocabulary and context?

**Comment by sgillies** [comment]
@ekansa no, won't add it to GeoJSON-LD, which is only about core GeoJSON elements, but maybe as a separate extension to that context.
